-- Create Config Table
create table public.config (
  key text primary key,
  value jsonb
);

-- Turn on RLS
alter table public.config enable row level security;

-- Admin Policy (Role 7)
create policy "Allow update for admins"
on public.config
for update
to authenticated
using ( (auth.jwt() ->> 'role')::int = 7 )
with check ( (auth.jwt() ->> 'role')::int = 7 );

-- Read Policy (All)
create policy "Allow read for all"
on public.config
for select
to authenticated
using ( true );

-- Initial Seed (Default Radius)
insert into public.config (key, value)
values ('max_radius_km', '0.2')
on conflict (key) do nothing;


-- Create Holidays Table
create table public.holidays (
  id bigint generated by default as identity primary key,
  data date not null,
  titulo text,
  tipo text default 'feriado'
);

-- Turn on RLS
alter table public.holidays enable row level security;

-- Read Policy (All)
create policy "Allow read for all"
on public.holidays
for select
to authenticated
using ( true );

-- Seed some holidays
insert into public.holidays (data, titulo)
values 
  ('2026-01-01', 'Confraternização Universal'),
  ('2026-04-21', 'Tiradentes'),
  ('2026-05-01', 'Dia do Trabalhador'),
  ('2026-09-07', 'Independência do Brasil'),
  ('2026-10-12', 'Nossa Senhora Aparecida'),
  ('2026-11-02', 'Finados'),
  ('2026-11-15', 'Proclamação da República'),
  ('2026-12-25', 'Natal')
on conflict do nothing;
